<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; El flujo de datos – Bendito maldito Linux</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../capitulos/cap04.html" rel="next">
<link href="../capitulos/cap02.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-93743b91ebf46552a17d53befe4b32bf.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f905219a99b525b35e5033ffd9a85ff1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/cap03.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El flujo de datos</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Bendito maldito Linux</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bienvenida</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Abrir la caja negra</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ficheros: tocar sin romper</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap03.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El flujo de datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">El árbol y los permisos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Paquetes y procesos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discos, particiones y arranque</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../anexos/anexo-windows.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Vengo de Windows</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#sec-canales" id="toc-sec-canales" class="nav-link active" data-scroll-target="#sec-canales"><span class="header-section-number">3.1</span> Los tres chorros</a></li>
  <li><a href="#sec-redirigir" id="toc-sec-redirigir" class="nav-link" data-scroll-target="#sec-redirigir"><span class="header-section-number">3.2</span> Redirigir: <code>&gt;</code> y <code>&gt;&gt;</code></a></li>
  <li><a href="#sec-tuberia" id="toc-sec-tuberia" class="nav-link" data-scroll-target="#sec-tuberia"><span class="header-section-number">3.3</span> La tubería: <code>|</code></a></li>
  <li><a href="#sec-herramientas" id="toc-sec-herramientas" class="nav-link" data-scroll-target="#sec-herramientas"><span class="header-section-number">3.4</span> La caja de herramientas</a></li>
  <li><a href="#sec-analisis" id="toc-sec-analisis" class="nav-link" data-scroll-target="#sec-analisis"><span class="header-section-number">3.5</span> El análisis, pieza a pieza</a></li>
  <li><a href="#sec-python" id="toc-sec-python" class="nav-link" data-scroll-target="#sec-python"><span class="header-section-number">3.6</span> ¿Y Python?</a></li>
  <li><a href="#sec-practica-3" id="toc-sec-practica-3" class="nav-link" data-scroll-target="#sec-practica-3"><span class="header-section-number">3.7</span> Práctica: la noche en el laboratorio</a></li>
  <li><a href="#sec-quiz-3" id="toc-sec-quiz-3" class="nav-link" data-scroll-target="#sec-quiz-3"><span class="header-section-number">3.8</span> Autocomprobación</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-cap03" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El flujo de datos</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="lede">
<p>Esta noche tu experimento ha generado un registro de 7 198 líneas. Nadie va a leerlas. Hoy aprendes el gesto que define a Unix desde hace cincuenta años: conectar programas pequeños como conectas aparatos en un montaje experimental, hasta que de un fichero inabarcable sale una respuesta de tres líneas.</p>
</div>
<div class="chapmeta">
<p>⏱ <strong>2–3 h</strong> con ejercicios · requisitos: <strong>capítulos 1 y 2</strong> · máquina: <strong>tu Linux de diario</strong></p>
</div>
<div class="objetivos">
<p><strong>Al terminar esta sesión sabrás</strong></p>
<ul>
<li>Qué son los tres canales de todo programa — stdin, stdout, stderr — y por qué esa separación es una idea brillante.</li>
<li>Guardar la salida de cualquier comando en un fichero con <code>&gt;</code> y <code>&gt;&gt;</code>, sin perder los errores por el camino.</li>
<li>Encadenar programas con la tubería <code>|</code>: la salida de uno como entrada del siguiente.</li>
<li>Usar la caja de herramientas del análisis: <code>wc</code>, <code>grep</code>, <code>sort</code>, <code>uniq</code> y <code>cut</code>.</li>
<li>Construir una tubería pieza a pieza, comprobando cada paso — el método que evita los errores silenciosos.</li>
<li>Decidir con criterio cuándo resolver algo con tuberías y cuándo abrir Python.</li>
</ul>
</div>
<section id="sec-canales" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-canales"><span class="header-section-number">3.1</span> Los tres chorros</h2>
<p>Todo programa de terminal, sin excepción, nace conectado a tres canales. Por uno le entra texto: la <strong>entrada estándar</strong> (<em>stdin</em>). Por otro escupe sus resultados: la <strong>salida estándar</strong> (<em>stdout</em>). Y por el tercero protesta: la <strong>salida de errores</strong> (<em>stderr</em>). Si no dices lo contrario, los tres apuntan a tu terminal: stdin al teclado, y las dos salidas a la pantalla.</p>
<div id="fig-canales" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Esquema de un programa con su entrada estándar desde el teclado y sus dos salidas, resultado y errores, hacia la pantalla">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-canales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../imagenes/cap03/fig-tres-chorros.svg" class="img-fluid figure-img" alt="Esquema de un programa con su entrada estándar desde el teclado y sus dos salidas, resultado y errores, hacia la pantalla">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-canales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Los tres canales, numerados 0, 1 y 2. La genialidad está en separar el resultado de las quejas.
</figcaption>
</figure>
</div>
<p>¿Por qué <em>dos</em> salidas? Piensa en el log de esta noche: si el programa de adquisición mezclara las medidas y los avisos de error en el mismo chorro, guardar los datos limpios sería un suplicio. Separados, puedes enviar cada uno a un sitio. Ese es exactamente el siguiente paso.</p>
</section>
<section id="sec-redirigir" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-redirigir"><span class="header-section-number">3.2</span> Redirigir: <code>&gt;</code> y <code>&gt;&gt;</code></h2>
<p>El símbolo <code>&gt;</code> desvía la salida estándar de la pantalla a un fichero. Descarga el registro de esta noche (está al final del capítulo, en la práctica) y prueba:</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep ERROR adquisicion.log &gt; errores.txt</span>
<span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">head -2 errores.txt</span>
<span class="t-out">2026-08-18 10:03:00 ERROR s3 sin respuesta del sensor</span>
<span class="t-out">2026-08-18 10:03:02 ERROR s3 sin respuesta del sensor</span></code></pre>
<p><code>grep</code> (lo conoces en un momento) no imprimió nada en pantalla: su stdout fue a parar a <code>errores.txt</code>. Dos reglas de seguridad:</p>
<ul>
<li><code>&gt;</code> <strong>sobrescribe</strong> el fichero de destino sin preguntar. Su hermano <code>&gt;&gt;</code> <strong>añade</strong> al final sin destruir lo anterior.</li>
<li>Los errores (stderr) <em>no</em> viajan con <code>&gt;</code>: siguen saliendo por pantalla, que es donde quieres verlos. Para capturarlos también existe <code>2&gt;</code> — el <code>2</code> es el número del canal de la figura.</li>
</ul>
<div id="fig-redireccion" class="quarto-float quarto-figure quarto-figure-center anchored" alt="El stdout de grep desviado con el símbolo mayor que hacia el fichero errores.txt, mientras el stderr sigue llegando a la pantalla">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-redireccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../imagenes/cap03/fig-redireccion.svg" class="img-fluid figure-img" alt="El stdout de grep desviado con el símbolo mayor que hacia el fichero errores.txt, mientras el stderr sigue llegando a la pantalla">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-redireccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.2: La misma escena que la figura anterior, con el desvío puesto: <code>&gt;</code> reconecta el stdout al fichero; el stderr ni se entera.
</figcaption>
</figure>
</div>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">echo "Informe de la noche" &gt; informe.txt</span>
<span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">echo "generado el 19 de agosto" &gt;&gt; informe.txt</span>
<span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">cat informe.txt</span>
<span class="t-out">Informe de la noche</span>
<span class="t-out">generado el 19 de agosto</span></code></pre>
<p><code>echo</code>, que conociste el primer día como un juguete, acaba de revelar su oficio real: fabricar líneas de texto para tus ficheros.</p>
</section>
<section id="sec-tuberia" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-tuberia"><span class="header-section-number">3.3</span> La tubería: <code>|</code></h2>
<p>Y aquí está la idea central del capítulo. Si <code>&gt;</code> conecta un programa con un fichero, la <strong>tubería</strong> <code>|</code> conecta un programa con <em>otro programa</em>: el stdout del de la izquierda se convierte en el stdin del de la derecha. Sin ficheros intermedios, sin pasos manuales.</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep ERROR adquisicion.log | wc -l</span>
<span class="t-out">108</span></code></pre>
<p>Léelo como una cadena de montaje: <code>grep</code> filtra las líneas con <code>ERROR</code>, y su salida — en vez de inundar la pantalla — entra en <code>wc -l</code> (<em>word count</em>, opción <em>lines</em>), que solo cuenta. De 7 198 líneas a un número: esta noche hubo 108 fallos.</p>
<div id="fig-pipe" class="quarto-float quarto-figure quarto-figure-center anchored" alt="El stdout de grep entra por una tubería en el stdin de wc, y solo el resultado final, 108, llega a la pantalla">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../imagenes/cap03/fig-pipe.svg" class="img-fluid figure-img" alt="El stdout de grep entra por una tubería en el stdin de wc, y solo el resultado final, 108, llega a la pantalla">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.3: El enchufe entre programas. Es la tercera manera de conectar el stdout: a la pantalla (por defecto), a un fichero (<code>&gt;</code>), o a otro programa (<code>|</code>).
</figcaption>
</figure>
</div>
<div class="historia">
<p><strong>◷ Historia · Una manguera de jardín en Bell Labs</strong></p>
<p>La tubería tiene padre: Doug McIlroy, jefe del departamento donde nació Unix. En 1964 — cinco años <em>antes</em> de Unix — ya escribía en un memorándum que los programas deberían acoplarse «como los tramos de una manguera de jardín: se enrosca otro segmento cuando hace falta tratar el agua de otra manera». Estuvo casi una década insistiendo, hasta que una noche de 1973 Ken Thompson cedió, la implementó en el kernel, y en una semana el equipo reescribió medio sistema en forma de filtros encadenables. De esa semana sale la <strong>filosofía Unix</strong> que estás usando ahora: haz que cada programa haga una sola cosa bien, y que todos hablen el mismo idioma — texto.</p>
</div>
</section>
<section id="sec-herramientas" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-herramientas"><span class="header-section-number">3.4</span> La caja de herramientas</h2>
<p>Cinco filtros bastan para el noventa por ciento del trabajo. Todos leen texto por stdin (o de un fichero que les des) y escriben texto por stdout — por eso encajan entre sí en cualquier orden:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Herramienta</th>
<th>Qué hace</th>
<th>La opción estrella</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>wc</code></td>
<td>cuenta</td>
<td><code>-l</code> solo líneas</td>
</tr>
<tr class="even">
<td><code>grep PATRON</code></td>
<td>deja pasar las líneas que contienen el patrón</td>
<td><code>-c</code> cuenta en vez de mostrar; <code>-v</code> invierte: las que NO lo contienen</td>
</tr>
<tr class="odd">
<td><code>sort</code></td>
<td>ordena las líneas</td>
<td><code>-n</code> numérico; <code>-r</code> al revés</td>
</tr>
<tr class="even">
<td><code>uniq</code></td>
<td>colapsa líneas repetidas <strong>adyacentes</strong></td>
<td><code>-c</code> antepone cuántas veces</td>
</tr>
<tr class="odd">
<td><code>cut</code></td>
<td>recorta columnas</td>
<td><code>-d' '</code> separador, <code>-f4</code> cuarto campo</td>
</tr>
</tbody>
</table>
<p>Y los que ya conoces, <code>head</code> y <code>tail</code>, también son filtros: al final de una tubería sirven para quedarte con lo primero o lo último.</p>
<div class="aviso">
<p><strong>△ Cuidado · <code>uniq</code> solo ve lo adyacente</strong></p>
<p><code>uniq</code> no busca repetidos por todo el fichero: colapsa líneas iguales <em>consecutivas</em>. Sueltas por ahí, se le escapan. Por eso el dúo inseparable es <code>sort | uniq</code>: primero juntas los iguales, luego colapsas. Si algún día un recuento te sale absurdo, revisa si te faltó el <code>sort</code>.</p>
</div>
</section>
<section id="sec-analisis" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-analisis"><span class="header-section-number">3.5</span> El análisis, pieza a pieza</h2>
<p>Vamos a responder la pregunta que un físico se hace ante ese log: <strong>¿qué sensor está fallando?</strong> Y vamos a hacerlo con el método profesional: construir la tubería paso a paso, mirando qué sale de cada pieza antes de añadir la siguiente.</p>
<p>Primer paso: aislar los errores y <em>mirar</em> unas cuantas líneas.</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep ERROR adquisicion.log | head -3</span>
<span class="t-out">2026-08-18 10:03:00 ERROR s3 sin respuesta del sensor</span>
<span class="t-out">2026-08-18 10:03:02 ERROR s3 sin respuesta del sensor</span>
<span class="t-out">2026-08-18 10:03:04 ERROR s3 sin respuesta del sensor</span></code></pre>
<p>El nombre del sensor es una columna. Contemos con los dedos sobre una línea: fecha (1), hora (2), nivel (3), <strong>sensor (4)</strong>, mensaje (5 en adelante). Segundo paso: recortar esa columna… y comprobar.</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep ERROR adquisicion.log | cut -d' ' -f5 | head -3</span>
<span class="t-out">sin</span>
<span class="t-out">sin</span>
<span class="t-out">sin</span></code></pre>
<p>¿«sin»? Hemos cortado el campo 5 — la primera palabra del <em>mensaje</em> — en vez del 4. Este tropiezo está puesto aquí a propósito, porque es el error más típico del capítulo y porque el método lo ha cazado al instante: <strong>cada pieza nueva se comprueba con un <code>head</code> antes de seguir</strong>. Corregimos y ahora sí:</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep ERROR adquisicion.log | cut -d' ' -f4 | head -3</span>
<span class="t-out">s3</span>
<span class="t-out">s3</span>
<span class="t-out">s3</span></code></pre>
<p>Tercer paso: de 108 nombres de sensor al recuento. Los iguales juntos (<code>sort</code>), colapsados contando (<code>uniq -c</code>), y el ranking de mayor a menor (<code>sort -nr</code>):</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep ERROR adquisicion.log | cut -d' ' -f4 | sort | uniq -c | sort -nr</span>
<span class="t-out">     90 s3</span>
<span class="t-out">     15 s1</span>
<span class="t-out">      3 s4</span></code></pre>
<p>Veredicto en una línea: el sensor <strong>s3</strong> es el culpable con 90 fallos (un conector flojo, apostaría un físico), s1 tuvo una racha corta de lecturas corruptas y s4 apenas tres tropiezos. Este es el momento del capítulo: acabas de interrogar a 7 198 líneas con una sola orden.</p>
<div id="fig-tuberia" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Cadena de programas grep, cut, sort y uniq que transforma el log de 7198 líneas en un ranking de tres sensores">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tuberia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../imagenes/cap03/fig-tuberia.svg" class="img-fluid figure-img" alt="Cadena de programas grep, cut, sort y uniq que transforma el log de 7198 líneas en un ranking de tres sensores">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tuberia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.4: La tubería completa del análisis, con lo que fluye en cada tramo.
</figcaption>
</figure>
</div>
<div class="truco">
<p><strong>✚ Truco · La tubería perfecta no se memoriza: se pregunta</strong></p>
<p>Que no te intimide la de cinco piezas: es el ejemplo más completo del curso a propósito, para que veas el mecanismo entero de una vez. Tu día a día serán tuberías de dos o tres — y si esta la has entendido, ya sabes cómo funcionan todas. Y una verdad incómoda de toda CLI: <strong>olvidar las herramientas y sus opciones es normal</strong>, hasta para los veteranos. Está permitido pedirle a una inteligencia artificial que te construya el comando («¿cómo cuento los ERROR por sensor en este log?») — con la disciplina del físico: <em>lee</em> el comando que te proponga pieza a pieza, verifica con <code>man</code> o <code>--help</code> lo que no reconozcas, y jamás ejecutes a ciegas nada que lleve <code>sudo</code> o <code>rm</code>. Tú ya sabes leer comandos: la IA propone, tú dispones. Este oficio lo afinaremos en un anexo del curso.</p>
</div>
<p>¿Y las temperaturas? El valor viene como <code>temp_C=22.66</code>: un <code>=</code> de separador y <code>cut</code> lo recorta igual de bien. Máxima de la noche:</p>
<pre class="terminal"><code><span class="t-p">marcos@portatil</span><span class="t-dim">:</span><span class="t-hl">~/Descargas</span><span class="t-dim">$</span> <span class="t-cmd">grep INFO adquisicion.log | grep temp_C | cut -d'=' -f2 | sort -n | tail -1</span>
<span class="t-out">25.00</span></code></pre>
<p>25.00 justos — sospechosamente redondo. Cruza el dato: <code>grep -c WARN adquisicion.log</code> da 357 avisos de «saturada» del sensor s2. El sensor no midió 25.00: se quedó <em>clavado</em> en su tope mientras la temperatura real seguía subiendo. Dos tuberías te acaban de dar el diagnóstico completo del montaje: s3 se desconecta, s2 está derivando hasta saturar.</p>
<div class="por-dentro">
<p><strong>◉ Por dentro · ¿Y aquel renombrado en lote?</strong></p>
<p>En el capítulo 2 renombraste cinco runs a mano y prometimos algo mejor. La verdad completa: las tuberías transforman <em>texto</em>, no ejecutan una orden por cada fichero — para eso hacen falta los bucles del shell, que viven en el anexo de <em>scripting</em>. Pero ya tienes la mitad de la solución: <code>find . -name "*.csv"</code> te fabrica la <strong>lista</strong> sobre la que un bucle trabajaría. La tubería prepara el trabajo; el bucle lo remata. Todo llega.</p>
</div>
</section>
<section id="sec-python" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-python"><span class="header-section-number">3.6</span> ¿Y Python?</h2>
<p>La pregunta honesta: tú sabes NumPy — ¿no era más fácil en Python? El mismo recuento, en Python legible:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>recuento <span class="op">=</span> {}</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> linea <span class="kw">in</span> <span class="bu">open</span>(<span class="st">"adquisicion.log"</span>):</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">" ERROR "</span> <span class="kw">in</span> linea:</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        sensor <span class="op">=</span> linea.split()[<span class="dv">3</span>]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>        recuento[sensor] <span class="op">=</span> recuento.get(sensor, <span class="dv">0</span>) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sensor, n <span class="kw">in</span> <span class="bu">sorted</span>(recuento.items(), key<span class="op">=</span><span class="kw">lambda</span> kv: <span class="op">-</span>kv[<span class="dv">1</span>]):</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(n, sensor)</span></code></pre></div>
<p>Ocho líneas, mismo resultado (<code>90 s3 · 15 s1 · 3 s4</code> — comprobado). Entonces, ¿cuándo cada cosa?</p>
<ul>
<li><strong>Tubería</strong> cuando la pregunta es exploratoria y la respuesta cabe en pantalla: ¿cuántos?, ¿cuáles?, ¿quién más? Diez segundos, cero ficheros nuevos, y funciona idéntica en el superordenador al que te conectes por SSH — donde quizá no puedas instalar nada.</li>
<li><strong>Python</strong> cuando empieza el <em>cálculo</em>: estadística, ajustes, gráficas, o cualquier análisis que mañana querrás repetir con otros datos. Un script se documenta y se cita; una tubería se teclea y se olvida.</li>
</ul>
<p>El flujo real de un físico computacional es la secuencia de ambos: explorar con tuberías hasta entender qué hay, y entonces escribir el script de Python que lo analiza en serio. Las dos herramientas no compiten: se turnan.</p>
</section>
<section id="sec-practica-3" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-practica-3"><span class="header-section-number">3.7</span> Práctica: la noche en el laboratorio</h2>
<p>Arranca tu cuaderno (<code>script sesion03.log</code>) y descarga el registro de la noche: <a href="../datos/cap03/adquisicion.log" download="adquisicion.log"><code>adquisicion.log</code></a> (305 KB de texto — ni se te ocurra abrirlo con doble clic: para eso está la sesión de hoy). Trabaja en <code>~/Descargas</code> o muévelo a tu carpeta de física del capítulo 2.</p>
<div class="ejercicio">
<p><strong>Ejercicio 3.1 · Dimensiones del problema</strong></p>
<p>¿Cuántas líneas tiene el log? ¿Cuántas corresponden al sensor <code>s2</code>? Pista para lo segundo: el patrón de <code>grep</code> puede llevar espacios si lo proteges con comillas — y <code>s2</code> con espacios alrededor evita confundirlo con cualquier otra cosa.</p>
<div class="solucion">
<div class="callout callout-style-default callout-tip callout-titled" title="Solución razonada">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución razonada
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>wc -l adquisicion.log</code> → 7 198. Y <code>grep -c " s2 " adquisicion.log</code> → 1 799.</p>
<p><strong>Por qué así</strong> — Las comillas protegen los espacios del patrón (son los mismos espacios-separadores del capítulo 1). Sin ellos, <code>s2</code> también casaría en cualquier línea que contuviera esa pareja de caracteres en otro sitio. Acotar el patrón es la mitad del oficio de <code>grep</code>.</p>
</div>
</div>
</div>
</div>
</div>
<div class="ejercicio">
<p><strong>Ejercicio 3.2 · El primer síntoma</strong></p>
<p>¿A qué hora exacta empezó a fallar el primer sensor, y cuál fue? Resuélvelo con una tubería que termine en <code>head</code>.</p>
<div class="solucion">
<div class="callout callout-style-default callout-tip callout-titled" title="Solución razonada">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución razonada
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>grep ERROR adquisicion.log | head -1</code> → <code>2026-08-18 10:03:00 ERROR s3 sin respuesta del sensor</code>. El s3, a las 10:03:00 — tres minutos después de arrancar.</p>
<p><strong>Por qué así</strong> — El log ya está en orden cronológico, así que «el primer error» es literalmente la primera línea que pase el filtro. Cuando el orden te lo dan hecho, aprovéchalo: ni <code>sort</code> ni nada.</p>
</div>
</div>
</div>
</div>
</div>
<div class="ejercicio">
<p><strong>Ejercicio 3.3 · ¿Quién avisa?</strong></p>
<p>Los <code>WARN</code> son avisos, no fallos. ¿Qué sensores emitieron avisos esta noche? La respuesta debe ser la lista de nombres, sin repetir.</p>
<div class="solucion">
<div class="callout callout-style-default callout-tip callout-titled" title="Solución razonada">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución razonada
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>grep WARN adquisicion.log | cut -d' ' -f4 | sort | uniq</code> → <code>s2</code>, solo. (Con <code>uniq -c</code> verás además que fueron 357 avisos.)</p>
<p><strong>Por qué así</strong> — Misma maquinaria que el ranking del capítulo, sin el <code>-c</code>: cuando solo quieres saber <em>quiénes</em>, <code>sort | uniq</code> es la pregunta «¿qué valores distintos hay en esta columna?». Apréndetela como frase hecha: la usarás mil veces.</p>
</div>
</div>
</div>
</div>
</div>
<div class="ejercicio">
<p><strong>Ejercicio 3.4 · La reconstrucción</strong></p>
<p>Sin mirar la sección del análisis: reconstruye de memoria la tubería del ranking de errores por sensor, pieza a pieza, comprobando cada paso con <code>head</code>. Compara tu resultado con el del capítulo.</p>
<div class="solucion">
<div class="callout callout-style-default callout-tip callout-titled" title="Solución razonada">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución razonada
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>grep ERROR adquisicion.log | cut -d' ' -f4 | sort | uniq -c | sort -nr</code> → <code>90 s3 · 15 s1 · 3 s4</code>.</p>
<p><strong>Por qué así</strong> — Si te salió a la primera, perfecto. Si no, mejor aún: el objetivo era practicar el método — añadir una pieza, <code>head</code>, mirar, seguir. Una tubería no se escribe: se <em>cultiva</em>. El día que te salga una de seis etapas habrás llegado sin darte cuenta.</p>
</div>
</div>
</div>
</div>
</div>
<div class="ejercicio">
<p><strong>Ejercicio 3.5 · Rango de temperaturas</strong></p>
<p>¿Entre qué mínima y máxima se movieron las lecturas <em>válidas</em> (las líneas <code>INFO</code>)? ¿Y por qué la máxima debe mirarse con lupa?</p>
<div class="solucion">
<div class="callout callout-style-default callout-tip callout-titled" title="Solución razonada">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución razonada
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Mínima: <code>grep INFO adquisicion.log | grep temp_C | cut -d'=' -f2 | sort -n | head -1</code> → 20.45. Máxima: la misma tubería con <code>tail -1</code> → 25.00. Y 25.00 es justo el tope donde s2 satura (los 357 <code>WARN</code>): la «máxima» no es una medida, es el techo del instrumento.</p>
<p><strong>Por qué así</strong> — <code>sort -n</code> ordena como números (sin <code>-n</code>, <code>9</code> iría después de <code>25</code>, orden alfabético). Y la lección de física: un valor sospechosamente redondo en el extremo del rango huele a saturación, no a dato. La tubería te dio el número; el criterio lo pones tú.</p>
</div>
</div>
</div>
</div>
</div>
<div class="ejercicio">
<p><strong>Ejercicio 3.6 · El informe</strong></p>
<p>Construye un fichero <code>informe.txt</code> con tres secciones usando solo <code>echo</code> y redirecciones: una línea de título, el total de errores, y el ranking por sensor. Las dos primeras con <code>echo</code> (una crea el fichero, la otra añade); la tercera, añadiendo la salida de tu tubería del 3.4.</p>
<div class="solucion">
<div class="callout callout-style-default callout-tip callout-titled" title="Solución razonada">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución razonada
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>echo "Informe de adquisicion - 18 de agosto" &gt; informe.txt
grep -c ERROR adquisicion.log &gt;&gt; informe.txt
grep ERROR adquisicion.log | cut -d' ' -f4 | sort | uniq -c | sort -nr &gt;&gt; informe.txt</code></pre>
<p>Comprueba con <code>cat informe.txt</code>: título, <code>108</code>, y las tres líneas del ranking.</p>
<p><strong>Por qué así</strong> — Primera línea con <code>&gt;</code> (crea o vacía el fichero) y el resto con <code>&gt;&gt;</code> (añaden). Si hubieras usado <code>&gt;</code> en todas, cada orden habría borrado la anterior y el informe tendría solo el ranking. Ese matiz — crear una vez, añadir después — es la gramática de todo informe generado por comandos. Cierra el cuaderno con <code>exit</code> y guarda <code>sesion03.log</code>.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-quiz-3" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-quiz-3"><span class="header-section-number">3.8</span> Autocomprobación</h2>
<p>Marca una respuesta por pregunta; la corrección es inmediata.</p>
<div class="quiz" id="quiz-cap03">
  <div class="qz"><p class="qq" data-n="1">En <code>grep ERROR log | wc -l</code>, la tubería conecta…</p>
    <label><input type="radio" name="z1" value="a"><span>el stdout de <code>grep</code> con el stdin de <code>wc</code></span></label>
    <label><input type="radio" name="z1" value="b"><span>el stderr de <code>grep</code> con la pantalla</span></label>
    <label><input type="radio" name="z1" value="c"><span>los dos programas con el fichero <code>log</code></span></label>
    <div class="fb good"><b>Correcto.</b> La salida estándar del de la izquierda se convierte en la entrada estándar del de la derecha. El fichero solo lo lee <code>grep</code>.</div>
    <div class="fb bad"><b>No exactamente.</b> La tubería une stdout→stdin entre programas; el fichero es asunto de <code>grep</code>, y stderr va por su propio canal. Revisa la figura de los tres chorros.</div>
  </div>
  <div class="qz"><p class="qq" data-n="2">¿Por qué <code>uniq -c</code> casi siempre lleva un <code>sort</code> delante?</p>
    <label><input type="radio" name="z2" value="a"><span>porque <code>uniq</code> solo colapsa repetidos adyacentes</span></label>
    <label><input type="radio" name="z2" value="b"><span>porque <code>uniq</code> exige entrada numérica</span></label>
    <label><input type="radio" name="z2" value="c"><span>por costumbre: sin <code>sort</code> da lo mismo</span></label>
    <div class="fb good"><b>Correcto.</b> Sin ordenar antes, los repetidos dispersos se le escapan y el recuento sale mal — el clásico error silencioso.</div>
    <div class="fb bad"><b>No exactamente.</b> <code>uniq</code> solo ve líneas iguales <em>consecutivas</em>: el <code>sort</code> previo junta los iguales para que el recuento sea completo.</div>
  </div>
  <div class="qz"><p class="qq" data-n="3">Ejecutas dos veces <code>echo hola &gt; f.txt</code>. ¿Qué contiene <code>f.txt</code>?</p>
    <label><input type="radio" name="z3" value="a"><span>dos líneas con «hola»</span></label>
    <label><input type="radio" name="z3" value="b"><span>una sola línea con «hola»</span></label>
    <label><input type="radio" name="z3" value="c"><span>depende del contenido anterior</span></label>
    <div class="fb good"><b>Correcto.</b> <code>&gt;</code> sobrescribe cada vez: la segunda ejecución vació el fichero y volvió a escribir. Para acumular, <code>&gt;&gt;</code>.</div>
    <div class="fb bad"><b>No exactamente.</b> <code>&gt;</code> sobrescribe sin preguntar — cada ejecución deja el fichero solo con su línea. El que añade es <code>&gt;&gt;</code>.</div>
  </div>
  <div class="qz"><p class="qq" data-n="4">¿Qué hace <code>cut -d' ' -f4</code>?</p>
    <label><input type="radio" name="z4" value="a"><span>recorta los 4 primeros caracteres de cada línea</span></label>
    <label><input type="radio" name="z4" value="b"><span>se queda con el cuarto campo, separando por espacios</span></label>
    <label><input type="radio" name="z4" value="c"><span>elimina la cuarta columna y deja el resto</span></label>
    <div class="fb good"><b>Correcto.</b> <code>-d</code> fija el separador y <code>-f</code> elige el campo. Y ya sabes qué pasa si cuentas mal los campos: se comprueba con un <code>head</code>.</div>
    <div class="fb bad"><b>No exactamente.</b> <code>cut</code> trocea cada línea por el separador de <code>-d</code> y entrega el campo que pide <code>-f</code>: aquí, el cuarto.</div>
  </div>
  <div class="qz"><p class="qq" data-n="5">Quieres guardar los resultados en un fichero pero seguir viendo los errores en pantalla. ¿Qué canal captura <code>2&gt;</code>?</p>
    <label><input type="radio" name="z5" value="a"><span>stderr, la salida de errores</span></label>
    <label><input type="radio" name="z5" value="b"><span>stdout, la salida estándar</span></label>
    <label><input type="radio" name="z5" value="c"><span>stdin, la entrada</span></label>
    <div class="fb good"><b>Correcto.</b> El 2 es el número de stderr (0=stdin, 1=stdout). Con <code>&gt;</code> a un fichero y sin tocar el 2, consigues justo eso: datos guardados, quejas visibles.</div>
    <div class="fb bad"><b>No exactamente.</b> La numeración es 0=stdin, 1=stdout, 2=stderr — <code>2&gt;</code> desvía las quejas. Vuelve a la figura de los tres chorros.</div>
  </div>
  <div class="qz"><p class="qq" data-n="6">¿Cuál es el equivalente exacto de <code>grep ERROR log | wc -l</code>?</p>
    <label><input type="radio" name="z6" value="a"><span><code>grep -c ERROR log</code></span></label>
    <label><input type="radio" name="z6" value="b"><span><code>wc -l ERROR log</code></span></label>
    <label><input type="radio" name="z6" value="c"><span><code>sort ERROR log | uniq -c</code></span></label>
    <div class="fb good"><b>Correcto.</b> <code>grep -c</code> cuenta las líneas que casan, ahorrándose la tubería. Muchos filtros tienen estos atajos — se descubren en su <code>man</code>.</div>
    <div class="fb bad"><b>No exactamente.</b> El atajo es <code>grep -c</code>: cuenta en vez de mostrar. Mismo resultado, una pieza menos.</div>
  </div>
</div>
<script>
(function(){
  const OK = {z1:"a", z2:"a", z3:"b", z4:"b", z5:"a", z6:"a"};
  document.querySelectorAll("#quiz-cap03 .qz input").forEach(i => {
    i.addEventListener("change", () => {
      const qz = i.closest(".qz");
      qz.classList.remove("ok","ko");
      qz.classList.add(i.value === OK[i.name] ? "ok" : "ko");
    });
  });
})();
</script>
<div class="solucion-final">
<p><strong>Autocomprobación (test de la sección 3.8)</strong> — Respuestas: 1 a · 2 a · 3 b · 4 b · 5 a · 6 a.</p>
</div>
<div class="proxima">
<p><strong>La próxima sesión</strong></p>
<p>Con el bloque A completo, ya <em>hablas</em> con la máquina. En el capítulo 4 empieza el bloque B: abrir el capó. El mapa completo del árbol — qué vive de verdad en <code>/etc</code>, <code>/var</code>, <code>/usr</code> —, quién es <code>root</code>, qué significa exactamente ese <code>sudo</code> que tecleas con fe, y el sistema de permisos <code>rwx</code> que llevas viendo en cada <code>ls -l</code> sin leerlo. Guarda <code>sesion03.log</code>: tres medidas ya en tu cuaderno.</p>
</div>
<div class="pie-piloto">
<p>cap. 3 v0.1 · piloto — anota tiempo real invertido, dudas y erratas junto a tu <code>sesion03.log</code></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/cap02.html" class="pagination-link" aria-label="Ficheros: tocar sin romper">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ficheros: tocar sin romper</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../capitulos/cap04.html" class="pagination-link" aria-label="El árbol y los permisos">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">El árbol y los permisos</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Claudio M. Martínez Velasco · Texto bajo licencia CC BY-SA 4.0</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>